(() => {
  'use strict';

  const menu = document.querySelector('.menu-toggle');
  const nav = document.getElementById('primary-nav');
  const mobile = window.matchMedia('(max-width: 900px)');

  if (menu && nav) {
    menu.hidden = false;
    document.body.classList.add('nav-enhanced');
    const closeMenu = () => {
      menu.setAttribute('aria-expanded', 'false');
      nav.classList.remove('is-open');
    };
    menu.addEventListener('click', () => {
      const open = menu.getAttribute('aria-expanded') !== 'true';
      menu.setAttribute('aria-expanded', String(open));
      nav.classList.toggle('is-open', open);
    });
    nav.addEventListener('click', event => {
      const link = event.target.closest('a');
      if (!link) return;
      closeMenu();
      if (mobile.matches) {
        // Move keyboard focus out of the now-collapsed navigation.
        const target = document.querySelector(link.getAttribute('href'));
        if (target) {
          target.setAttribute('tabindex', '-1');
          target.focus({ preventScroll: true });
        }
      }
    });
    document.addEventListener('keydown', event => {
      if (event.key === 'Escape' && menu.getAttribute('aria-expanded') === 'true') {
        closeMenu();
        menu.focus();
      }
    });
    document.addEventListener('click', event => {
      if (!event.target.closest('.topbar')) closeMenu();
    });
    mobile.addEventListener('change', closeMenu);
  }

  // Footnotes open their FAQ answer on click, direct link, and back/forward.
  const openLinkedFaq = () => {
    const answer = document.getElementById(window.location.hash.slice(1));
    if (!answer || !answer.matches('details.qa')) return;
    answer.open = true;
    answer.scrollIntoView({ block: 'start' });
    answer.querySelector('summary').focus({ preventScroll: true });
  };
  document.querySelectorAll('.footnote-ref').forEach(link => {
    link.addEventListener('click', event => {
      event.preventDefault();
      if (window.location.hash === link.hash) openLinkedFaq();
      else window.location.hash = link.hash;
    });
  });
  window.addEventListener('hashchange', openLinkedFaq);
  openLinkedFaq();

  // Actual, unedited CareDraft outputs supplied by the owner.
  // Nursing example supplied September 27, 2026.
  // PT: 7:04 AM; OT: 7:23 AM. Preserve the exported wording.
  const examples = {
    "sn": {
      "title": "Skilled nursing · post-operative visit",
      "transcript": "SN SNV to home for post-op f/u, WC, & med mgmt w/ CG present. Pt A&O, CP & GI stable, V/S WNL. Incision cleaned & redressed per MD orders; staples intact, (-) s/sx of infxn, tol well. Meds rec’d, planner pre-poured, pt/CG edu on s/sx infxn & fluid overload w/ good return verbalization. Pt remains HB d/t dec mobility & AD dep for safe amb. Cont SN per POC.",
      "note": "The patient was seen in the home for post-operative follow-up, wound care, and medication management with the caregiver present. The patient was alert and oriented with stable cardiopulmonary and gastrointestinal status and vital signs within normal limits. The incision was cleaned and redressed per physician orders; staples were intact with no signs or symptoms of infection, and the patient tolerated the procedure well. Medications were received, and the planner was pre-poured. The patient and caregiver received education on signs of infection and fluid overload with good verbal return. The patient remains homebound due to decreased mobility and dependence on ADs for safe ambulation. Continued skilled nursing is indicated per the plan of care.",
      "kind": "Generated by CareDraft AI"
    },
    "pt": {
      "title": "Physical therapy · routine visit",
      "transcript": "PT f/u. Pt reports easier chair transfers, still unsteady with turns. Gait w RW, CGA; better foot clearance after cues. Practiced sit-to-stand, less UE push-off. Continue skilled gait/balance work per POC.",
      "note": "The patient was seen for a physical therapy follow-up visit and reports easier chair transfers, though they remain unsteady with turns. Gait was observed with a rolling walker, requiring contact guard assist, with improved foot clearance following cues. Skilled intervention included sit-to-stand practice, noting decreased upper extremity push-off. Continued skilled physical therapy is indicated to progress gait and balance work as outlined in the plan of care.",
      "kind": "Generated by CareDraft AI"
    },
    "ot": {
      "title": "Occupational therapy · self-care visit",
      "transcript": "OT f/u. LB dressing w reacher, min A. Sequencing better after demo. Standing self-care limited by fatigue; pacing/rest cues helped. Needs reinforcement for independent carryover. Cont per POC.",
      "note": "The patient was seen for an occupational therapy follow-up visit. Dressing, specifically lower body dressing, was completed with the use of a reacher and minimal assistance, with sequencing improving following demonstration. Standing self-care remains limited by fatigue, and pacing and rest cues were helpful in managing this. The patient requires reinforcement to promote independent carryover of skills. The plan of care will continue as established.",
      "kind": "Generated by CareDraft AI"
    }
  };

  const buttons = document.querySelectorAll('[data-example]');
  const transcript = document.getElementById('demo-transcript');
  const note = document.getElementById('demo-note');
  const noteTitle = document.getElementById('demo-note-title');
  const exampleKind = document.getElementById('demo-kind');
  if (buttons.length && transcript && note && noteTitle && exampleKind) {
    document.body.classList.add('demo-enhanced');
    buttons.forEach(button => {
      button.addEventListener('click', () => {
        const example = examples[button.dataset.example];
        if (!example) return;
        buttons.forEach(item => item.setAttribute('aria-pressed', String(item === button)));
        transcript.textContent = '“' + example.transcript + '”';
        noteTitle.textContent = example.title;
        note.textContent = example.note;
        exampleKind.textContent = example.kind;
      });
    });
  }

  const year = document.getElementById('year');
  if (year) year.textContent = String(new Date().getFullYear());
})();
